"""The inbox index: answering "what arrived today?".

Filing by delivery date is right for the archive and wrong for the daily
question it is meant to answer. After the machine has been off for three days,
the newly downloaded documents land in three past directories and today's
directory can look empty -- exactly when there is the most to read.

So each run writes `_inbox/{today}.md`, keyed on the *download* date, linking
into the delivery-date directories with relative paths.

An index rather than symlinks, deliberately: it works over SMB and on Windows
without link privileges, it duplicates nothing, and when purge removes a
directory the index for that day goes with it instead of leaving broken links.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from contextlib import suppress
from dataclasses import dataclass
from datetime import date
from urllib.parse import quote

from ..clock import RetentionWindow, timestamp, to_dir_name, today
from ..config import Config
from ..manifest.repo import ManifestDocument, ManifestRepo

log = logging.getLogger(__name__)


@dataclass
class InboxReport:
    path: str | None = None
    documents: int = 0
    written: bool = False


def _link(document: ManifestDocument) -> str:
    """A relative link from `_inbox/x.md` to the document, URL-escaped.

    The `..` is what makes it work from inside `_inbox/`. Escaping matters
    because the names carry characters that Markdown viewers otherwise mangle.
    """
    return "../" + quote((document.path or "").replace("\\", "/"))


def _describe(document: ManifestDocument) -> str:
    parts = [part for part in (document.category, document.doc_type, document.species) if part]
    # The three fields overlap: the type often repeats the category, and species
    # is empty outside assemblies. Deduplicate while preserving order.
    seen: set[str] = set()
    unique = [p for p in parts if not (p.lower() in seen or seen.add(p.lower()))]
    return " / ".join(unique) or "Document"


def render(documents: list[ManifestDocument], *, for_date: date, window: RetentionWindow) -> str:
    """Render the index. Grouped by delivery date, newest first."""
    by_delivery: dict[str, list[ManifestDocument]] = defaultdict(list)
    for document in documents:
        by_delivery[document.delivery_date].append(document)

    lines = [
        f"# Documents downloaded on {to_dir_name(for_date)}",
        "",
        f"{len(documents)} document(s), grouped by the date they were filed at Fundos.NET.",
        f"Retention window: {window} ({window.days} day(s), including today).",
        "",
    ]

    if not documents:
        lines += [
            "Nothing new arrived today.",
            "",
            "That is not necessarily a problem: many funds go days without publishing.",
            "",
        ]

    for delivery_date in sorted(by_delivery, reverse=True):
        group = by_delivery[delivery_date]
        suffix = " — today" if delivery_date == to_dir_name(for_date) else ""
        lines.append(f"## {delivery_date}{suffix} ({len(group)})")
        lines.append("")
        for document in sorted(group, key=lambda d: (d.fund_description or "", d.document_id)):
            name = document.fund_description or f"entity {document.fundosnet_id}"
            reference = f" · ref. {document.reference_date}" if document.reference_date else ""
            version = f" · v{document.version}" if document.version > 1 else ""
            status = (
                f" · **{document.status}**"
                if document.status and "ativo" not in document.status.lower()
                else ""
            )
            lines.append(
                f"- [{name}]({_link(document)}) — {_describe(document)}{reference}{version}{status}"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"Generated by fii-docs-watcher at {timestamp()}.")
    lines.append("")
    return "\n".join(lines)


def run(repo: ManifestRepo, config: Config, window: RetentionWindow) -> InboxReport:
    """Write today's index from what was actually downloaded today."""
    for_date = today()
    since = f"{to_dir_name(for_date)}T00:00:00"
    documents = [
        document
        for document in repo.downloaded_since(since)
        # A document delivered outside the window is on its way out; linking to
        # it would produce an index entry that purge is about to invalidate.
        if window.contains_str(document.delivery_date)
    ]

    inbox_dir = config.paths.inbox_dir
    inbox_dir.mkdir(parents=True, exist_ok=True)
    # A share may refuse chmod outright; the index is still worth writing.
    with suppress(OSError):
        inbox_dir.chmod(config.files.directory_mode)

    path = inbox_dir / f"{to_dir_name(for_date)}.md"
    path.write_text(render(documents, for_date=for_date, window=window), encoding="utf-8")
    with suppress(OSError):
        path.chmod(config.files.file_mode)

    log.info(
        "inbox index written",
        extra={"file": path.name, "documents": len(documents)},
    )
    return InboxReport(
        path=str(path.relative_to(config.paths.documents_root)),
        documents=len(documents),
        written=True,
    )
